### ISSUE TITLE
Exclusive mode no longer works with Anniversary Update

### ISSUE THREAD

**Issue by lbacud** [irungentoo/Xiaomi_gamepad#12]
Since I updated to the new Windows 10 anniversary Update, the app no longer goes into exclusive mode.

**Comment by fanliv** [comment]
Same Here windows 10 Anniversary Update 
`VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&2704ae31&9&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
Could not open gamepad in exclusive mode. Please close anything that could be using the controller
Attempting to open it in shared mode.
1 controllers connected`

**Comment by lbacud** [comment]
Well, based on this video, https://inputmapper.com/20-windows-10-1607-au-exclusive-mode-fix I found that it has much to do with how Windows deals with HID devices once they are connected. I was able to get it back in exclusive mode by going into Device Manager after connecting the controller to bluetooth, but before turning on the app. Disabling and re-enabling the "Bluetooth HID Device" which matches the controller and starting the app. Hopefully there would be a way around this in the next release.

**Comment by adms-design** [comment]
Not working for me this hid device on-off method :(

**Comment by irungentoo** [comment]
Try and find out which new windows thing is opening the gamepad then uninstall it or prevent it from starting.

**Comment by lbacud** [comment]
https://inputmapper.com/21-windows-10-anniversary-update-why-things-broke says the problem is in kernel32.dll, so we can do neither. If you haven't updated to the Anniversary update and use this app, don't update to the AU.

**Comment by mentionmenot** [comment]
Having same issuse. Since Annivesary update, some of games reconize both of two controllers (Xbox 360 emu and Xiaomi gamepad). That causes the conflic buttons during the game like Ace Combat Assault Horizon.

**Comment by luminousmazim** [comment]
You can use this app with AU update. I have this issue since redstone insider build, but I found workaround to fix this problem. 
- Open Device Manager 
- Expand Human Interface Devices 
- Disable HID-Compliant game controller (If you have 2 list, close program before. If program not running, re-open and close it) 
- Do Scan hardware changes (in Action menu) | Actually this step not entirely necessary, just to refresh list.
- Enable HID-Compliant game controller again.
- Then open program (mi.exe)

No issue or so whatever so far, just when you used gamepad after a while (week, or month depend on your battery power) Vibrating can make your gamepad turn off instantly. But work fine if your turn off vibrate feature in game. Just when vibrate, boom turn off. Sorry my bad English.

**Comment by irungentoo** [comment]
This is why I hate windows. The only way to "fix" it is some dumb workaround by disabling and re enabling the device driver.

> Just when vibrate, boom turn off.

See: https://github.com/irungentoo/Xiaomi_gamepad/issues/11

**Comment by tu-nv** [comment]
Nothing we can do except trying the above workaround and hope this will be fixed in the next windows update.

**Comment by irungentoo** [comment]
Fixed in latest release.
